version: 2
jobs:
  python3:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: build using python3.6
          command: |
            pip3 install .
      - run:
          name: test using python3.6
          command: |
            pip3 install nose
            nosetests tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - python3
