
batch: "./config/batch/simple.yaml"
external: "./config/external/conll_lample_weak.yaml"
model: "./config/model/lample.yaml"
optimizer: "./config/optimizer/adam.yaml"
preprocessing: "./config/preprocessing/simple.yaml"
output: "model/lample"
