external: "./config/external/conll2003.skipngram.yaml"
iteration: "./config/iteration/long.yaml"
model: "./config/model/lample.yaml"
optimizer: "./config/optimizer/adabound.yaml"
preprocessing: "./config/preprocessing/znorm.yaml"
output: "./model/conll2003.lample.skipngram.adabound"
