# training data
data_dir: "./pyner/tool/corpus/data/processed/CoNLL2003_BIOES"

# pre-trained word vectors
word_vector: "./pyner/tool/vector/data/processed/Skip100/model"

# additional vocabulary
vocab.words.txt: "./pyner/tool/vector/data/processed/Skip100/vocab.words.txt"
